kind: pipeline
name: default

steps:
  - name: install
    image: node:alpine
    commands:
      - yarn install

  - name: build
    image: node:alpine
    commands:
      - yarn build
    depends_on:
      - install

  - name: node-10
    image: node:10-alpine
    commands:
      - yarn test:unit
    depends_on:
      - build

  - name: node-11
    image: node:11-alpine
    commands:
      - yarn test:unit
    depends_on:
      - build

  - name: node-12
    image: node:12-alpine
    commands:
      - yarn test:unit
    depends_on:
      - build

  - name: node-13
    image: node:12-alpine
    commands:
      - yarn test:unit
    depends_on:
      - build

  - name: browsers
    image: node:13-buster
    commands:
      - yarn test:browsers
    depends_on:
      - build

  - name: coverage-build
    image: node:alpine
    commands:
      - yarn test:coverage
    depends_on:
      - node-10
      - node-11
      - node-12
      - node-13
      - browsers

  - name: coverage-report
    image: plugins/codecov
    settings:
      token:
        from_secret: CODECOV_TOKEN
    depends_on:
      - coverage-build
